export const PREFIJO_ALMACENAMIENTO = 'precio_justo_'

export const CLAVE_COMERCIOS = 'comercios'
export const CLAVE_CONTADOR_GRACIAS = 'contadorGracias'
export const CLAVE_LISTA_JUSTA = 'lista_justa'
export const CLAVE_PREFERENCIAS_USUARIO = 'preferencias_usuario'
export const CLAVE_SESION_ESCANEO = 'sesion_escaneo'
export const CLAVE_CACHE_FIRESTORE_COMERCIOS_META = 'cacheFirestoreComerciosMeta'
export const CLAVE_CACHE_FIRESTORE_LISTAS_META = 'cacheFirestoreListasMeta'
export const CLAVE_CACHE_FIRESTORE_MESA_META = 'cacheFirestoreMesaMeta'
export const CLAVE_CACHE_FIRESTORE_PREFERENCIAS_META = 'cacheFirestorePreferenciasMeta'
export const CLAVE_CACHE_FIRESTORE_PRODUCTOS_META = 'cacheFirestoreProductosMeta'
export const CLAVE_MIGRACION_PREFERENCES_LEGACY_META = 'migracionPreferencesLegacyMeta'

export const PREFIJO_BACKUP_MIGRACION_FIREBASE = 'backupMigracionFirebase_'
export const PREFIJO_COLA_SINCRONIZACION = 'colaSincronizacion_'
export const PREFIJO_CONFIRMACIONES = 'confirmaciones_'
export const PREFIJO_DECISION_MIGRACION_LOCAL_FIREBASE = 'decisionMigracionLocalFirebase_'
export const PREFIJO_FOTOS_LOCALES = 'fotoLocal_'
export const PREFIJO_PRODUCTOS = 'producto_'
